### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by dartar** [OpenScienceRoadmap/OpenScienceRoadmap.github.io#1]
Consider switching to HTTPS.

**Comment by xolotl** [comment]
Now that [GitHub pages with custom domains support HTTPS](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/), we've been considering it, but we also consider [arguments that HTTPS isn't necessarily needed in every context](http://scripting.com/2014/08/08/myBlogDoesntNeedHttps.html), especially for sites that do not collect information even though there are still security concerns even for informational sites.

If the community feels strongly that the JROST site should move to HTTPS, we can do it.

**Please indicate your support for moving to HTTPS with a thumbs up vote on this issue, or a thumbs down to remain with HTTP.**

**Comment by xolotl** [comment]
jrost.org has now been enabled to require HTTPS

Documentation used:
https://help.github.com/articles/securing-your-github-pages-site-with-https/
https://help.github.com/articles/troubleshooting-custom-domains/#https-errors
